#!/usr/bin/env python3
from PIL import Image, ImageDraw, ImageFont
import pathlib

FONT = '/System/Library/Fonts/SFHebrew.ttf'
SIZE = 96
OVERSAMPLE = 4
FILL = 0.72
LETTERS = [('nun', 'נ'), ('gimel', 'ג'), ('he', 'ה'), ('shin', 'ש')]

root = pathlib.Path(__file__).resolve().parent.parent
out = root / 'src' / 'props' / 'hebrew_glyph_data.c'


def render(char):
    big = SIZE * OVERSAMPLE
    font = ImageFont.truetype(FONT, int(big * FILL))
    tile = Image.new('L', (big, big), 0)
    draw = ImageDraw.Draw(tile)
    stroke = OVERSAMPLE * 2
    left, top, right, bottom = draw.textbbox((0, 0), char, font=font, stroke_width=stroke)
    width, height = right - left, bottom - top
    scale = min(1.0, big * FILL / max(width, height))
    if scale < 1.0:
        font = ImageFont.truetype(FONT, int(big * FILL * scale))
        left, top, right, bottom = draw.textbbox((0, 0), char, font=font, stroke_width=stroke)
        width, height = right - left, bottom - top
    draw.text(((big - width) // 2 - left, (big - height) // 2 - top), char, font=font,
              fill=255, stroke_width=stroke, stroke_fill=255)
    small = tile.resize((SIZE, SIZE), Image.LANCZOS)
    return small.transpose(Image.FLIP_TOP_BOTTOM)


def pack(image):
    pixels = image.load()
    data = []
    for y in range(SIZE):
        for x in range(0, SIZE, 8):
            byte = 0
            for bit in range(8):
                if pixels[x + bit, y] >= 128:
                    byte |= 0x80 >> bit
            data.append(byte)
    return data


lines = ['/* Generated by tools/gen-glyphs.py from SF Hebrew; do not edit by hand. */',
         '#include "hebrew_glyphs.h"', '',
         'const unsigned char hebrew_glyph_bits[HEBREW_GLYPH_COUNT][HEBREW_GLYPH_BYTES] = {']
for index, (name, char) in enumerate(LETTERS):
    data = pack(render(char))
    lines.append(f'    /* {name} */')
    lines.append('    {')
    for offset in range(0, len(data), 16):
        chunk = ', '.join(f'0x{b:02x}' for b in data[offset:offset + 16])
        lines.append(f'        {chunk},')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('    }' + (',' if index < len(LETTERS) - 1 else ''))
lines.append('};')
out.write_text('\n'.join(lines) + '\n')
print(f'wrote {out.relative_to(root)}')
